### ISSUE TITLE
How to enable multi-line dot matching?

### ISSUE THREAD

**Issue by Silex** [joddie/pcre2el#13]
Hello,

Is there a way to set the flags so dot matches newline for functions like `pcre-query-replace-regexp` or `pcre-mode`? For now I used `(.|\n)` but it's a bit annoying.

**Comment by joddie** [comment]
This is now available in the `master` version.  You should be able to toggle the `s`, `x`, and `i` flags in the minibuffer using `C-c s`, `C-c x`, and `C-c i`.  Hope this helps!
