### ISSUE TITLE
Needless quoting of *?

### ISSUE THREAD

**Issue by Wilfred** [joddie/pcre2el#14]
Given the string `"a*?"`, `rxt-elisp-to-rx` gives `(*\? "a")`. This works, but I think it should return `(*? "a")`.

**Comment by joddie** [comment]
This should now be fixed in master.  We have to re-implement `print` anyway for `rx` forms to print nicely, so special-casing these symbols is not too bad.  Thanks for the report!

**Comment by joddie** [comment]
It occurs to me that if you use `eval-last-sexp` or similar to print the value of `(rxt-elisp-to-rx "a*?")`, you will still see the escaped `*\?`.  There's not much we can do about that, but now `rxt-explain-elisp` and `rxt-toggle-elisp-rx` should at least display these forms without the extra backslash.
