### ISSUE TITLE
pcre-mode breaks isearch wrapping in hexl-mode

### ISSUE THREAD

**Issue by asmeurer** [joddie/pcre2el#18]
In hexl-mode, isearch-forward automatically wraps around the displayed line. When I enable pcre-mode, this breaks, and it only searches the text on the screen. For now I have

```elisp
(pcre-mode 1)
(defun turn-off-pcre ()
  (interactive)
  (pcre-mode 0))

(add-hook 'hexl-mode-hook 'turn-off-pcre)
``` 

in my `.emacs`, but it would be nice to have it working (or at the very least, disabled automatically).

**Comment by joddie** [comment]
Thanks for the report.  On a cursory look, it seems like `hexl-mode` also changes isearch behavior by setting the `isearch-search-function` variable, so one of the two modes will clobber the other.  I guess this will probably need to be special-cased in `pcre-isearch-search-fun-function`.

Do you see this problem when searching with regexps, or just plain text search, or both?

**Comment by joddie** [comment]
Looking at `hexl-isearch-search-function`, it looks like the wrapping behavior is only enabled for plain-text search: regexp searches do not wrap in any case.  So it would probably be enough for pcre-mode's isearch function to fall back to hexl-mode's version when hexl-mode is enabled and the search is not regexp-based.

**Comment by joddie** [comment]
I think this should be fixed now, please re-open if not.  This fix should also enable other modes with special isearch behavior to continue working, as long as it does not involve regexp search.

**Comment by asmeurer** [comment]
Yes, it appears to work now.
