### ISSUE TITLE
Handle `query-replace-from-to-separator' correctly

### ISSUE THREAD

**Issue by Silex** [joddie/pcre2el#28]
Hello,

In Emacs 25.1 `query-replace-regexp` is enhanced, see http://endlessparentheses.com/new-in-emacs-25-1-query-replace-history-is-enhanced-.html

Currently `pcre-mode` breaks `query-replace-regexp` because the interactive spec does not handle the case when you reuse a previous history of `foo -> bar`

**Comment by dchenbecker** [comment]
For what it's worth, at least in Emacs 26.1, enabling pcre-mode will allow the normal query-replace-regex to handle PCRE properly, and it also properly handles the separator.

**Comment by Silex** [comment]
True, I forgot I had this issue open.
