### ISSUE TITLE
`preceding-sexp` is deprecated use `elisp-preceding-sexp`

### ISSUE THREAD

**Issue by jasonm23** [joddie/pcre2el#39]
https://github.com/joddie/pcre2el/blob/0b5b2a2c173aab3fd14aac6cf5e90ad3bf58fa7d/pcre2el.el#L558

**Comment by NetMage** [comment]
That should be `elisp--preceding-sexp`.

**Comment by hardaker** [comment]
Supposedly fixed by PR46
