### ISSUE TITLE
pcre2el.el:1042:13:Warning: looking-back called with 1 argument, but requires 2-3

### ISSUE THREAD

**Issue by NetMage** [joddie/pcre2el#41]
In rxt-toggle-elisp-rx:  pcre2el.el:1042:13:Warning: looking-back called with 1 argument, but requires 2-3

Need to add `nil` to the call to `looking-back` to indicate no limit:

    ((looking-back "\"" nil) (backward-sexp))

**Comment by hardaker** [comment]
Supposedly fixed by PR46
